- queenbee/cli.py
- queenbee/schema/arguments.py
- queenbee/schema/artifact_location.py
- queenbee/schema/dag.py
- queenbee/schema/function.py
- queenbee/schema/operator.py
- queenbee/schema/parser.py
- queenbee/schema/qutil.py
- queenbee/schema/workflow.py
- tests/assets/workflow_example/daylightfactor.yaml
- tests/conftest.py
- tests/schema/arguments_test.py
- tests/schema/artifact_location_test.py
- tests/schema/function_test.py
- tests/schema/operator_test.py
- tests/schema/workflow_test.py
I added this is as I was encountering issues with Argo whereby I wanted to set the path of an artifact to be `argo/pollination/job/{{ workflow.id}}`.
I could have written these methods in the other repo but this felt like the kind of thing we should add to queenbee.
I also added some minor fix to pydantic enums (deleted them :stuck_out_tongue: ) and added one-line doc to the `validate` command.
> Workflow hydration

- .travis.yml
To be able to get the version we need to install the latest version of queenbee from pip before creating the docs.
> fix(docs): add pip install

- queenbee/schema/arguments.py
- queenbee/schema/info.py
- queenbee/schema/metadata.py
- queenbee/schema/workflow.py
- tests/schema/metadata.py
Info closely follows the openapi info object. It allows users to add description, version, license and contact information to a workflow. A couple of notes:
- I kept the name of the workflow as is not to make a breaking change. It might be a better implementation to move it under info.
- All the field are currently optional but we might want to make versioning required.
- Should we consider a license by default? Something like MIT or BSD?
I added user_data field separate from the other arguments input since I _feel_ it serves a different purpose and should be on its own. The current implementation accepts a dictionary and is optional.
> Add new fields for info and user_data

- docs/MANIFEST.in
- setup.py
The template yaml files for cli was missing from the package.
> build(setup.py): add cli assets to build

- README.md
- docs/guides/repository.rst
- queenbee/cli/recipe/install.py
- queenbee/cli/recipe/new.py
- queenbee/cli/repository/index.py
- queenbee/cli/repository/serve.py
The only real bug was using  `local-queenbee-argo` instead of `local-queenbee-repo` in one of the commands.
> docs(repository): improve documentation

- queenbee/base/io.py
- queenbee/recipe/dependency.py
- queenbee/recipe/recipe.py
- queenbee/repository/index.py
- queenbee/repository/package.py
This PR fixes two issues with recipe and dependency creation:
1. The URL handling for Windows is fixed.
2. The package URL is fixed.
@AntoineDao, the package_url was missing the subfolder. <s>Not sure if you like my implementation. I added it in the object when it returns the url but it can also be implemented in operator index.json itself to have the full url. `operators/energy-plus-0.1.0.tgz` instead of `energy-plus-0.1.0.tgz`.</s>
It was `http://localhost:8000/energy-plus-0.1.0.tgz` but should have been `http://localhost:8000/operators/energy-plus-0.1.0.tgz`
> Recipe review

- queenbee/recipe/recipe.py
If some cases dependencies are only recipes and there is no operator folder. In those cases queenbee should not try to list the files in a nonresistant folder.
> fix(recipe-dep): add extra checks before collecting dependencies

- queenbee/recipe/artifact_source.py
This was causing an issue with the documentation: https://travis-ci.org/github/ladybug-tools/queenbee/jobs/708701110#L536
I believe this is a result of the recent change in how Pydantic works with Enum objects. We can use the Enum trick anymore. The good news is that `constr` is there to help.
cc: @AntoineDao, @chriswmackey
> fix(artifacts_source): replace Enum with constr in type

- queenbee/recipe/dag.py
- queenbee/recipe/reference.py
Added support for fixed value for artifact argument for a task. This is similar to what a parameter argument supports and is the minimum change that I need to be able to get the daylight-factor results aggregate work.
We need to add support for this in queenbee extensions.
Resolves #121
> fix(task): add support for fixed value in task artifact arguments

- queenbee/recipe/dag.py
- tests/assets/recipes/baked/daylight-factor.yaml
- tests/assets/recipes/baked/parametric-daylight-factor.yaml
- tests/assets/recipes/folders/daylight-factor/flow/main.yaml
- tests/assets/recipes/folders/parametric-daylight-factor/flow/main.yaml
This is a temporary solution to provide type information for recipe/dag inputs.
I tried to fix the tests and compared them locally. The main challenge is that the digest between the two doesn't match. Not sure if there is an easy fix for that. Secretly hoping that the tests are going to pass here! 😀
> feat(dag): add annotations field

- docs/schemas/recipes.rst
- queenbee/base/request.py
- queenbee/cli/recipe/package.py
- queenbee/cli/repository/init.py
- queenbee/cli/repository/manage.py
- queenbee/cli/repository/search.py
- queenbee/config/repositories.py
- queenbee/recipe/recipe.py
- queenbee/repository/index.py
- queenbee/repository/package.py
There are two commits that are related to development issues here:
- One that fixes the path issues for Windows path
- A second one that fixes the path for accessing the local resources
With these fixes I could create a local index and get `queenbee repo list` to work. Once this is merged I need to:
1. Send a new PR to honeybee-radiance-recipe repository with the new file structure.
2. Add a new command to Queenbee luigi to support the new way of getting the recipe from a repository instead of a baked recipe file.
3. Use the new command the Grasshopper component to deal with honeybee-radiance recipes.
> Fixes in order to get the local indexing to work

- dev-requirements.txt
- docs.py
- queenbee/io/alias.py
- queenbee/io/common.py
- requirements.txt
- tests/assets/recipes/baked/daylight-factor.yaml
- tests/assets/recipes/baked/parametric-daylight-factor.yaml
- tests/assets/recipes/folders/daylight-factor/flow/main.yaml
- tests/assets/recipes/valid/daylight-factor.yaml
This PR adds alias object for inputs and outputs that allows the recipe author to assign pre/post processing for each input/output in different client side applications like Grasshopper, Rhino, etc.
After testing different ideas I ended up adding an alias input/output type for each input/output. This will allow the developers to create a new valid input/output for the target platform with no limitations. The handler will take care of converting the alias input to the original input.
> Add alias input and output objects

- docs.py
- queenbee/io/alias.py
- queenbee/io/dag.py
- queenbee/io/function.py
This is mainly for clarification purpose. @MingboPeng found it confusing to call this type object considering what object type means in Python and C#.
> rename DAGObject to DAGJSONObject

- queenbee/base/basemodel.py
The BaseModelNoType should not have any extra keys otherwise these keys will be translated to extensions which might not be desired.
> fix(basemodel): move annotations field to Queenbee BaseModel

- queenbee/io/inputs/node.py
- queenbee/io/outputs/node.py
- queenbee/workflow/status.py
These i/o types are used to link the original template input or output with the value generated by the task/workflow that has been run.
> feat(status): add node status i/o primitives

- queenbee/job/job.py
- queenbee/job/status.py
- queenbee/plugin/plugin.py
- queenbee/recipe/recipe.py
- queenbee/repository/index.py
This PR addresses the JobStatus I/O types issue and proposes an api versioning scheme set on specific object.
API versioning should only be set ofData Transfer Objects (DTOs) are any object that we expect to be used to be used by an external API (ie: not-queenbee) to be parsed and computed.
I have opted for a version and maturity flag for API versions (ie: version = v1 and maturity = beta1). This versioning scheme should ideally work like described for the Kubernetes project: https://kubernetes.io/docs/concepts/overview/kubernetes-api/#api-groups-and-versioning
fix #209
> Status and version

- queenbee/base/metadata.py
- queenbee/plugin/plugin.py
- queenbee/recipe/recipe.py
- queenbee/repository/package.py
This PR removes the license file and uses the license field in meta data instead as the single source of declaring a license for a plugin or a recipe.
Resolves #154
> fix(license): remove license file

- queenbee/io/outputs/alias.py
I realized that we should use the from_ field from the output itself for the handler.
> fix(output alias): remove redundant from field

- queenbee/base/basemodel.py
Now that we use queenee DSL to write the recipes and  the schema is stable we can relax the check and allow additional fields.
This will make it possible to support non-breaking changes for schema on Pollination.
> fix(basemodel): allow extra fields in Queenbee objects

- queenbee/io/common.py
- queenbee/io/inputs/alias.py
- queenbee/io/inputs/dag.py
- queenbee/io/outputs/alias.py
- queenbee/io/outputs/dag.py
- tests/assets/functions/valid/function.yaml
- tests/assets/functions/valid/function_optional_input.yaml
- tests/assets/functions/valid/function_optional_output.yaml
- tests/assets/recipes/valid/optional-input-output.yaml
This commit adds support for optional artifact inputs and outputs. This change will make it possible to support radiance recipes with BSDF materials.
@AntoineDao, I added an `is_optional` property to artifact input/outputs which can be used to update the extensions to support optional types.
> add optional artifact

- queenbee/plugin/plugin.py
- queenbee/recipe/recipe.py
The current settings was removing the default values for type and as a result all the values were written to folder as string type.
> fix: include unset values in recipes when written to folder

- queenbee/base/request.py
- queenbee/config/repositories.py
- queenbee/recipe/dependency.py
- queenbee/repository/package.py
This PR addresses the issue with resolving the local path as a uri. It took mixed usage of `os.path` and `pathlib.Path` to get it right on both Windows and Linux. Part of the issue was how in Windows and \*nix systems based on what the uri is pointing to the number of slashes after file:// can be 2 or 3! I was expecting it to always be 3 which would return `home/user/...` instead of `/home/user/...`. The first one is considered an absolute path and the second one is relative! That's the main reason that it was failing. I also took the opportunity to clean the code a little bit.
resolves #266
> fix: resolve local dependency path on \*nix correctly

- queenbee/base/basemodel.py
- queenbee/io/inputs/dag.py
This changes ensures the warning for optional artifacts will only be printed in valid cases.
> style(optional artifact):  catch the cause for misleading warning

- requirements.txt
- tests/base/hash_test.py
- tests/operator/operator_test.py
- tests/recipe/recipe_test.py
Pydantic 1.8 breaks the hashing functions somehow. I think we should move to 1.8 once they have
fixed that bug. I am also not sure how to go about testing this bug reliably to avoid future
dependencies update that cause a similar bug...
#280
> fix(deps): revert to pydantic 1.7.3

- queenbee/job/job.py
- queenbee/job/run.py
- queenbee/job/status.py
This makes it clearer what status strings to expect and helps generate more robust SDK clients.
> fix(status): enumerate job/run/step status strings

- queenbee/io/common.py
One of the creative usage of handlers that [came up](https://github.com/pollination/pollination-alias/blob/21a0db5569c739cfb4f0de6a1dc8b3f1721bfd4c/pollination/alias/outputs/daylight.py#L25-L38) during the development was to use handlers one after another. Luckily the current schema could support this case:
```python
OutputAlias.linked(
name='results',
platform=['rhino'],
handler=[
IOAliasHandler(
language='python',
module='pollination_handlers.outputs.daylight',
function='read_df_from_folder'
),
IOAliasHandler(
language='csharp', module='Pollination.RhinoHandlers',
function='LoadMeshBasedResultsToRhino'
)
]
)
```
The current implementation doesn't indicate which handler should be executed first. In this case since @MingboPeng was the developer of both the Rhino plugin and the Alias he …
> feat(handler): add index field to support chained handlers

- .devcontainer/Dockerfile
- dev-requirements.txt
- queenbee/job/job.py
- tests/job/job_test.py
This PR addresses underlying issues with Job Argument validation.
> Validate run arguments

- requirements.txt
LBT libraries are moved to 1.9.0 and without updating the dependency here we will have conflict issues for local runs.
> fix(deps): bump pydantci to 1.9.0

- .github/workflows/ci.yaml
- requirements.txt
We are using an old token from the LBT organization for this repository. This PR updates that and should fix the deployment.
> Fix deployment

- queenbee/job/run.py
This type is mainly used by Argo containerset.
> fix(status): add support for Container status type

- queenbee/io/outputs/step.py
Unlike Function outputs, DAG outputs don't have a default field for `path`. This commit fixes that issue.
> fix(step outputs): support translating DAG artifact outputs

- .github/workflows/ci.yaml
Apparently username and password is no longer a supported deployment method: https://github.com/pollination/queenbee/actions/runs/9054289912/job/24873984153#step:8:3423
@mostaphaRoudsari , could I get you to add a new PyPi API Token scoped to this repository and name is `PYPI_TOKEN`? Here are the instructions to create the token: https://pypi.org/help/#apitoken
I suspect this is created and managed by the ladybugbot account. This is part of some upgrades I am making that will allow me to upgrade pollination server to python 3.12.
> ci(pypi): use PyPi token instead of username and password

- queenbee/base/basemodel.py
We currently cast the value to string which make it hard to use the annotations dictionary to pass values in the correct type.
> fix(basemodel): allow any types for annotations value
