pollination/queenbee

- .gitignore
- README.md
@AntoineDao and @chriswmackey, While I'm working on the generator and validator code I thought I should share the documentation with you first and get some feedback. See the README.md.
@chriswmackey I know you haven't been involved in the process of coming up with this workflows much but this will actually make you a great candidate to give us some feedback. This workflow structure will be used for creating workflows for all the different packages.
PS: apparently this approach has a name and is called `Documentation Driven Development`!
> docs(readme): first draft for workflow documentation

- README.md
> style(readme): updated command section style

- .travis.yml
- queenbee/schema/status.py
This PR addresses the workflow status tracking primitives issue that will be used by plugins to provide a uniform debugging schema.
> Workflow Status Monitoring Schema

- .gitignore
- queenbee/schema/artifact_location.py
- queenbee/schema/function.py
- queenbee/schema/workflow.py
- tests/assets/arguments.yaml
- tests/assets/function_int_input.yaml
- tests/assets/workflow_example/daylightfactor.yaml
- tests/schema/function_test.py
- tests/schema/workflow_test.py
- Fixed the validator to allow integer inputs for arguments.
- Made several PEP8 fixes and corrected a number of misspellings.
> fix(function): support integer inputs

- README.md
- queenbee/schema/arguments.py
- queenbee/schema/artifact_location.py
- queenbee/schema/dag.py
- queenbee/schema/function.py
- queenbee/schema/parser.py
- queenbee/schema/qutil.py
- queenbee/schema/variable.py
- queenbee/schema/workflow.py
- tests/assets/arguments_dup_name.yaml
- tests/assets/function.yaml
- tests/assets/parameters.yaml
- tests/assets/workflow_example/daylightfactor.yaml
- tests/schema/arguments_test.py
- tests/schema/parameters_test.py
- tests/schema/workflow_test.py
- Added new validators
- Fixed the bug for finding workflow artifacts.
- Added new methods to Argument, Parameter and Artifact classes to make it easy to access and validate the input values
- Moved input validation to Arguments level so we can validate them before adding them to the workflow.
- Added new tests for Parameter.
- Added a new module for queenbee variables.
This PR partially breaks workflow hydrate which I will fix in the next PR.
resolves #12, resolves #19, resolves #11
> Improved validators and documentation

- queenbee/schema/arguments.py
- queenbee/schema/artifact_location.py
- queenbee/schema/dag.py
- queenbee/schema/function.py
- queenbee/schema/operator.py
- queenbee/schema/parser.py
- queenbee/schema/qutil.py
- queenbee/schema/status.py
- queenbee/schema/variable.py
- queenbee/schema/workflow.py
- setup.py
- tests/assets/workflow_example/daylightfactor.yaml
- tests/assets/workflow_example/daylightfactor_invalid_location.yaml
- tests/schema/arguments_test.py
- tests/schema/artifact_location_test.py
- tests/schema/dag_test.py
- tests/schema/function_test.py
- tests/schema/parameters_test.py
- tests/schema/workflow_test.py
I'm sending this PR mainly to show the process to @MingoPeng but I also wanted the last changes to be part of the tests that @AntoineDao is doing on the simulation service.
> Add more validations to workflow

- docs/guides/operator.rst
- docs/guides/repository.rst
- queenbee/_openapi.py
- queenbee/cli/operator/package.py
- queenbee/cli/recipe/package.py
- queenbee/cli/repository/__init__.py
- queenbee/cli/repository/index.py
- queenbee/cli/repository/initialise.py
- queenbee/cli/repository/serve.py
- queenbee/repository/index.py
This PR Contains docs and slight CLI interface change to package operators/recipes and index repositories.
> Packaging and Repository Indexing

- queenbee/cli/recipe/install.py
- queenbee/recipe/recipe.py
Thanks for spotting this @mostaphaRoudsari !
> fix(recipe): don't lock dependencies when writing folder

- .travis.yml
- queenbee/cli/recipe/package.py
- requirements.txt
- tests/assets/recipes/baked/daylight-factor.yaml
> chore(deps): change `~= ` to `==`

- queenbee/recipe/dag.py
- tests/assets/recipes/invalid/dag-task-parameter-null.error
- tests/assets/recipes/invalid/dag-task-parameter-null.yaml
- tests/assets/recipes/invalid/sub-folder-incorrect-ref.yaml
- tests/assets/recipes/valid/sub-folder.yaml
- tests/base/_base.py
- tests/base/folder_test.py
I found this bug while updating daylight recipes. Once merged we can push the new recipe.
> fix(dag): fix validation for arguments value

- queenbee/base/request.py
- setup.py
This fixes the bug that we hit during the demo this morning.
> fix request from a remote url

- .dependabot/config.yml
- dev-requirements.txt
I am also updating the dev-requirements to work with the new pip.
> fix(deps): Add dependabot and trigger release with Pydantic 1.7.2

- .gitignore
This is a commit to show Devang how to use GitKraken - I will merge it in as is.
> chore(gitignore): add hack.py to gitignore

- queenbee/job/job.py
- queenbee/job/status.py
- queenbee/plugin/plugin.py
- queenbee/recipe/recipe.py
- queenbee/repository/index.py
> fix(schema): make api_version read-only in schema

- queenbee/io/common.py
- queenbee/io/inputs/alias.py
- queenbee/io/inputs/dag.py
- queenbee/io/inputs/function.py
- queenbee/io/inputs/step.py
- queenbee/io/outputs/step.py
Array should only be from a parameter type
> fix(array io): remove artifact types from array ItemTypes

- .github/workflows/ci.yaml
- .releaserc.json
- docs/conf.py
- gen_schemas.py
> fix: fix version discrepancy 

- queenbee/base/request.py
- queenbee/env/os.py
- Add `env` module for environment-specific values
- Use in `request` module for local files
- To DRY up the code
- To fix #269
> feat(env): Add env module

- queenbee/recipe/task.py
- tests/assets/recipes/invalid/duplicate_args.error
- tests/assets/recipes/invalid/duplicate_args.yaml
- tests/assets/recipes/invalid/duplicate_returns.error.txt
- tests/assets/recipes/invalid/duplicate_returns.yaml
> fix(task): add validation check for duplicated arguments and returns

- queenbee/config/repositories.py
- queenbee/io/inputs/alias.py
- queenbee/io/inputs/dag.py
Resolves #287
I also took the chance to remove the unnecessary and confusing warning for optional artifacts.
> Add missing type for RepositoryReference

- README.md
> fix(readme): Update schema URLs

- queenbee/io/common.py
- queenbee/io/inputs/alias.py
- queenbee/io/inputs/dag.py
- tests/assets/recipes/baked/pollination-annual-daylight-optional-alias.yaml
fixes #305,
also fixes this issue: https://github.com/pollination/annual-daylight/runs/2153634990
> Improve alias validations

- .github/workflows/ci.yaml
> fix(ci): update GitHub action
